const fs = require("fs");
const process = require("process");

if (!fs.existsSync("./package.json")) throw new Error("must be at root");
const outPath = process.argv[2];
if (outPath == null) throw new Error("specify output file");

const input = fs.readFileSync("./src/server/common_types.ts", { encoding: "utf-8" });
const replaced = "/* do not edit manually -- auto-generated by gen_common_types.js */" + input.replace(/\/\* #begin-export\r?\n(.*)\r?\n\*\//s, "$1");
fs.writeFileSync(outPath, replaced, { encoding: "utf-8" });